--VISTA ES LO MISMO QUE  UNA TABLA
--UNA VISTA  PUEDE 
--LOS DATOS DE LOS EMPLEADOS SIN EL SALARIO NI COMISION, DIR.
CREATE OR REPLACE VIEW V_EMPLEADOS
AS
    SELECT  EMP_NO,  APELLIDO, OFICIO, FECHA_ALT, DEPT_NO from EMP;

SELECT * FROM  V_EMPLEADOS;